# Generated by Django 4.0.2 on 2022-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
