# Generated by Django 4.0.2 on 2022-02-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_latitude_remove_property_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Property Log'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name_plural': 'Property Type'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Region'},
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Onsale', 'Onsale'), ('Sold', 'Sold'), ('Reserved', 'Reserved')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
