# Generated by Django 4.0.2 on 2022-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_currency_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
