# Generated by Django 4.0.2 on 2022-02-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
