# Generated by Django 4.0.2 on 2022-02-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='properttype',
            new_name='propertytype',
        ),
    ]
