# Generated by Django 4.0.2 on 2022-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_rename_properttype_property_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Onsale', 'Onsale'), ('Sold', 'Sold'), ('Reserved', 'Reserved')], max_length=50, null=True),
        ),
    ]
